name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  ci:
    name: CI checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable pnpm

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install packages
        run: pnpm i --frozen-lockfile

      - name: Run tests
        run: pnpm test:mutation

      - name: Run lint
        run: pnpm lint

  node-compat-tests:
    name: Compat tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable pnpm

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install packages
        run: pnpm i --frozen-lockfile

      - name: Run tests
        run: pnpm t
