name: Publish

on:
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/ci-workflow.yaml

  publish:
    name: Publish
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable pnpm

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org

      - name: Install packages
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --access public
