name: Publish

on:
  workflow_dispatch:

jobs:
  verify:
    uses: ./.github/workflows/ci-workflow.yaml

  publish:
    name: Publish
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: npm publish --access public
